// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: modules/favorite/favoritePb/favoritePb.proto

package RetroPGF_Hub_Backend_Go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FavGrpcServiceClient is the client API for FavGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavGrpcServiceClient interface {
	GetAllFavByUserId(ctx context.Context, in *GetAllFavProjectReq, opts ...grpc.CallOption) (*GetAllFavRes, error)
}

type favGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavGrpcServiceClient(cc grpc.ClientConnInterface) FavGrpcServiceClient {
	return &favGrpcServiceClient{cc}
}

func (c *favGrpcServiceClient) GetAllFavByUserId(ctx context.Context, in *GetAllFavProjectReq, opts ...grpc.CallOption) (*GetAllFavRes, error) {
	out := new(GetAllFavRes)
	err := c.cc.Invoke(ctx, "/FavGrpcService/GetAllFavByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavGrpcServiceServer is the server API for FavGrpcService service.
// All implementations must embed UnimplementedFavGrpcServiceServer
// for forward compatibility
type FavGrpcServiceServer interface {
	GetAllFavByUserId(context.Context, *GetAllFavProjectReq) (*GetAllFavRes, error)
	mustEmbedUnimplementedFavGrpcServiceServer()
}

// UnimplementedFavGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFavGrpcServiceServer struct {
}

func (UnimplementedFavGrpcServiceServer) GetAllFavByUserId(context.Context, *GetAllFavProjectReq) (*GetAllFavRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFavByUserId not implemented")
}
func (UnimplementedFavGrpcServiceServer) mustEmbedUnimplementedFavGrpcServiceServer() {}

// UnsafeFavGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavGrpcServiceServer will
// result in compilation errors.
type UnsafeFavGrpcServiceServer interface {
	mustEmbedUnimplementedFavGrpcServiceServer()
}

func RegisterFavGrpcServiceServer(s grpc.ServiceRegistrar, srv FavGrpcServiceServer) {
	s.RegisterService(&FavGrpcService_ServiceDesc, srv)
}

func _FavGrpcService_GetAllFavByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFavProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavGrpcServiceServer).GetAllFavByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FavGrpcService/GetAllFavByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavGrpcServiceServer).GetAllFavByUserId(ctx, req.(*GetAllFavProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FavGrpcService_ServiceDesc is the grpc.ServiceDesc for FavGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FavGrpcService",
	HandlerType: (*FavGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllFavByUserId",
			Handler:    _FavGrpcService_GetAllFavByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/favorite/favoritePb/favoritePb.proto",
}
