// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: modules/favorite/favoritePb/favoritePb.proto

package RetroPGF_Hub_Backend_Go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type GetAllFavReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetAllFavReq) Reset() {
	*x = GetAllFavReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFavReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFavReq) ProtoMessage() {}

func (x *GetAllFavReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFavReq.ProtoReflect.Descriptor instead.
func (*GetAllFavReq) Descriptor() ([]byte, []int) {
	return file_modules_favorite_favoritePb_favoritePb_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllFavReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllFavRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string              `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Projects []*ProjectResForFav `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
}

func (x *GetAllFavRes) Reset() {
	*x = GetAllFavRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFavRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFavRes) ProtoMessage() {}

func (x *GetAllFavRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFavRes.ProtoReflect.Descriptor instead.
func (*GetAllFavRes) Descriptor() ([]byte, []int) {
	return file_modules_favorite_favoritePb_favoritePb_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllFavRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllFavRes) GetProjects() []*ProjectResForFav {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectResForFav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl        string `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	BannerUrl      string `protobuf:"bytes,4,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	WebsiteUrl     string `protobuf:"bytes,5,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	CryptoCategory string `protobuf:"bytes,6,opt,name=crypto_category,json=cryptoCategory,proto3" json:"crypto_category,omitempty"`
	Description    string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Reason         string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Category       string `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Contact        string `protobuf:"bytes,10,opt,name=contact,proto3" json:"contact,omitempty"`
	FavCount       int64  `protobuf:"varint,11,opt,name=fav_count,json=favCount,proto3" json:"fav_count,omitempty"`
	CommentCount   int64  `protobuf:"varint,12,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedBy      string `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      string `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ProjectResForFav) Reset() {
	*x = ProjectResForFav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectResForFav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResForFav) ProtoMessage() {}

func (x *ProjectResForFav) ProtoReflect() protoreflect.Message {
	mi := &file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResForFav.ProtoReflect.Descriptor instead.
func (*ProjectResForFav) Descriptor() ([]byte, []int) {
	return file_modules_favorite_favoritePb_favoritePb_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectResForFav) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectResForFav) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectResForFav) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ProjectResForFav) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *ProjectResForFav) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *ProjectResForFav) GetCryptoCategory() string {
	if x != nil {
		return x.CryptoCategory
	}
	return ""
}

func (x *ProjectResForFav) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectResForFav) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProjectResForFav) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProjectResForFav) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *ProjectResForFav) GetFavCount() int64 {
	if x != nil {
		return x.FavCount
	}
	return 0
}

func (x *ProjectResForFav) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ProjectResForFav) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ProjectResForFav) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_modules_favorite_favoritePb_favoritePb_proto protoreflect.FileDescriptor

var file_modules_favorite_favoritePb_favoritePb_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x2f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x50, 0x62, 0x2f, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x46, 0x61, 0x76, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x46, 0x6f, 0x72,
	0x46, 0x61, 0x76, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0xaa, 0x03,
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x46,
	0x61, 0x76, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x6f, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x72,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x72, 0x6c,
	0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61,
	0x76, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66,
	0x61, 0x76, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x43, 0x0a, 0x0e, 0x46, 0x61,
	0x76, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x76, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x76, 0x52, 0x65, 0x73, 0x42,
	0x26, 0x5a, 0x24, 0x52, 0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d, 0x48, 0x75, 0x62, 0x2f,
	0x52, 0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d, 0x48, 0x75, 0x62, 0x2d, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x47, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_favorite_favoritePb_favoritePb_proto_rawDescOnce sync.Once
	file_modules_favorite_favoritePb_favoritePb_proto_rawDescData = file_modules_favorite_favoritePb_favoritePb_proto_rawDesc
)

func file_modules_favorite_favoritePb_favoritePb_proto_rawDescGZIP() []byte {
	file_modules_favorite_favoritePb_favoritePb_proto_rawDescOnce.Do(func() {
		file_modules_favorite_favoritePb_favoritePb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_favorite_favoritePb_favoritePb_proto_rawDescData)
	})
	return file_modules_favorite_favoritePb_favoritePb_proto_rawDescData
}

var file_modules_favorite_favoritePb_favoritePb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_favorite_favoritePb_favoritePb_proto_goTypes = []interface{}{
	(*GetAllFavReq)(nil),     // 0: GetAllFavReq
	(*GetAllFavRes)(nil),     // 1: GetAllFavRes
	(*ProjectResForFav)(nil), // 2: ProjectResForFav
}
var file_modules_favorite_favoritePb_favoritePb_proto_depIdxs = []int32{
	2, // 0: GetAllFavRes.projects:type_name -> ProjectResForFav
	0, // 1: FavGrpcService.GetAllFavByUserId:input_type -> GetAllFavReq
	1, // 2: FavGrpcService.GetAllFavByUserId:output_type -> GetAllFavRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_favorite_favoritePb_favoritePb_proto_init() }
func file_modules_favorite_favoritePb_favoritePb_proto_init() {
	if File_modules_favorite_favoritePb_favoritePb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFavReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFavRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_favorite_favoritePb_favoritePb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectResForFav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_favorite_favoritePb_favoritePb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_favorite_favoritePb_favoritePb_proto_goTypes,
		DependencyIndexes: file_modules_favorite_favoritePb_favoritePb_proto_depIdxs,
		MessageInfos:      file_modules_favorite_favoritePb_favoritePb_proto_msgTypes,
	}.Build()
	File_modules_favorite_favoritePb_favoritePb_proto = out.File
	file_modules_favorite_favoritePb_favoritePb_proto_rawDesc = nil
	file_modules_favorite_favoritePb_favoritePb_proto_goTypes = nil
	file_modules_favorite_favoritePb_favoritePb_proto_depIdxs = nil
}
