version: '3.9'
name: retro-pgf-hub
services:

  users-db:
    image: mongo
    container_name: users-db
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/var/lib/mongo/users

  redis:
    image: redis:alpine3.19
    container_name: redis
    ports:
      - 6379:6379
    volumes:  
      - redis_data:/var/lib/redis
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf

volumes:
  mongo_data:
  redis_data: