// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: modules/datacenter/datacenterPb/datacenterPb.proto

package RetroPGF_Hub_Backend_Go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type GetProjectDataCenterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip  int64 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *GetProjectDataCenterReq) Reset() {
	*x = GetProjectDataCenterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectDataCenterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDataCenterReq) ProtoMessage() {}

func (x *GetProjectDataCenterReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDataCenterReq.ProtoReflect.Descriptor instead.
func (*GetProjectDataCenterReq) Descriptor() ([]byte, []int) {
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectDataCenterReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProjectDataCenterReq) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type GetSingleProjectDataCenterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjecId string `protobuf:"bytes,1,opt,name=projecId,proto3" json:"projecId,omitempty"`
}

func (x *GetSingleProjectDataCenterReq) Reset() {
	*x = GetSingleProjectDataCenterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleProjectDataCenterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleProjectDataCenterReq) ProtoMessage() {}

func (x *GetSingleProjectDataCenterReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleProjectDataCenterReq.ProtoReflect.Descriptor instead.
func (*GetSingleProjectDataCenterReq) Descriptor() ([]byte, []int) {
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP(), []int{1}
}

func (x *GetSingleProjectDataCenterReq) GetProjecId() string {
	if x != nil {
		return x.ProjecId
	}
	return ""
}

type GetProjectDataCenterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projects []*ProjectRes `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
}

func (x *GetProjectDataCenterRes) Reset() {
	*x = GetProjectDataCenterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectDataCenterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDataCenterRes) ProtoMessage() {}

func (x *GetProjectDataCenterRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDataCenterRes.ProtoReflect.Descriptor instead.
func (*GetProjectDataCenterRes) Descriptor() ([]byte, []int) {
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectDataCenterRes) GetProjects() []*ProjectRes {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetSingleProjectDataCenterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projects *ProjectRes `protobuf:"bytes,1,opt,name=projects,proto3" json:"projects,omitempty"`
}

func (x *GetSingleProjectDataCenterRes) Reset() {
	*x = GetSingleProjectDataCenterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleProjectDataCenterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleProjectDataCenterRes) ProtoMessage() {}

func (x *GetSingleProjectDataCenterRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleProjectDataCenterRes.ProtoReflect.Descriptor instead.
func (*GetSingleProjectDataCenterRes) Descriptor() ([]byte, []int) {
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP(), []int{3}
}

func (x *GetSingleProjectDataCenterRes) GetProjects() *ProjectRes {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl        string `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	BannerUrl      string `protobuf:"bytes,4,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	WebsiteUrl     string `protobuf:"bytes,5,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	CryptoCategory string `protobuf:"bytes,6,opt,name=crypto_category,json=cryptoCategory,proto3" json:"crypto_category,omitempty"`
	Description    string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Reason         string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Category       string `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Contact        string `protobuf:"bytes,10,opt,name=contact,proto3" json:"contact,omitempty"`
	FavCount       int64  `protobuf:"varint,11,opt,name=fav_count,json=favCount,proto3" json:"fav_count,omitempty"`
	CommentCount   int64  `protobuf:"varint,12,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedBy      string `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      string `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ProjectRes) Reset() {
	*x = ProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRes) ProtoMessage() {}

func (x *ProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRes.ProtoReflect.Descriptor instead.
func (*ProjectRes) Descriptor() ([]byte, []int) {
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectRes) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ProjectRes) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *ProjectRes) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *ProjectRes) GetCryptoCategory() string {
	if x != nil {
		return x.CryptoCategory
	}
	return ""
}

func (x *ProjectRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProjectRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProjectRes) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *ProjectRes) GetFavCount() int64 {
	if x != nil {
		return x.FavCount
	}
	return 0
}

func (x *ProjectRes) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ProjectRes) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ProjectRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProjectRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_modules_datacenter_datacenterPb_datacenterPb_proto protoreflect.FileDescriptor

var file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDesc = []byte{
	0x0a, 0x32, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50,
	0x62, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x22, 0x3b, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x48, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x22, 0xc3, 0x03, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x6f, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55,
	0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x72,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x61, 0x76, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x66, 0x61, 0x76, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xc1, 0x01, 0x0a, 0x15, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x12, 0x5c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1e,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x42, 0x26,
	0x5a, 0x24, 0x52, 0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d, 0x48, 0x75, 0x62, 0x2f, 0x52,
	0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d, 0x48, 0x75, 0x62, 0x2d, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2d, 0x47, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescOnce sync.Once
	file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescData = file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDesc
)

func file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescGZIP() []byte {
	file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescOnce.Do(func() {
		file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescData)
	})
	return file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDescData
}

var file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_datacenter_datacenterPb_datacenterPb_proto_goTypes = []interface{}{
	(*GetProjectDataCenterReq)(nil),       // 0: GetProjectDataCenterReq
	(*GetSingleProjectDataCenterReq)(nil), // 1: GetSingleProjectDataCenterReq
	(*GetProjectDataCenterRes)(nil),       // 2: GetProjectDataCenterRes
	(*GetSingleProjectDataCenterRes)(nil), // 3: GetSingleProjectDataCenterRes
	(*ProjectRes)(nil),                    // 4: ProjectRes
}
var file_modules_datacenter_datacenterPb_datacenterPb_proto_depIdxs = []int32{
	4, // 0: GetProjectDataCenterRes.projects:type_name -> ProjectRes
	4, // 1: GetSingleProjectDataCenterRes.projects:type_name -> ProjectRes
	0, // 2: DataCenterGrpcService.GetProjectDataCenter:input_type -> GetProjectDataCenterReq
	1, // 3: DataCenterGrpcService.GetSingleProjectDataCenter:input_type -> GetSingleProjectDataCenterReq
	2, // 4: DataCenterGrpcService.GetProjectDataCenter:output_type -> GetProjectDataCenterRes
	3, // 5: DataCenterGrpcService.GetSingleProjectDataCenter:output_type -> GetSingleProjectDataCenterRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_datacenter_datacenterPb_datacenterPb_proto_init() }
func file_modules_datacenter_datacenterPb_datacenterPb_proto_init() {
	if File_modules_datacenter_datacenterPb_datacenterPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectDataCenterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleProjectDataCenterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectDataCenterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleProjectDataCenterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_datacenter_datacenterPb_datacenterPb_proto_goTypes,
		DependencyIndexes: file_modules_datacenter_datacenterPb_datacenterPb_proto_depIdxs,
		MessageInfos:      file_modules_datacenter_datacenterPb_datacenterPb_proto_msgTypes,
	}.Build()
	File_modules_datacenter_datacenterPb_datacenterPb_proto = out.File
	file_modules_datacenter_datacenterPb_datacenterPb_proto_rawDesc = nil
	file_modules_datacenter_datacenterPb_datacenterPb_proto_goTypes = nil
	file_modules_datacenter_datacenterPb_datacenterPb_proto_depIdxs = nil
}
