// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: modules/comment/commentPb/commentPb.proto

package RetroPGF_Hub_Backend_Go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
}

func (x *CreateCommentProjectReq) Reset() {
	*x = CreateCommentProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_comment_commentPb_commentPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentProjectReq) ProtoMessage() {}

func (x *CreateCommentProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_comment_commentPb_commentPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentProjectReq.ProtoReflect.Descriptor instead.
func (*CreateCommentProjectReq) Descriptor() ([]byte, []int) {
	return file_modules_comment_commentPb_commentPb_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateCommentProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateCommentProjectRes) Reset() {
	*x = CreateCommentProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_comment_commentPb_commentPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentProjectRes) ProtoMessage() {}

func (x *CreateCommentProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_comment_commentPb_commentPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentProjectRes.ProtoReflect.Descriptor instead.
func (*CreateCommentProjectRes) Descriptor() ([]byte, []int) {
	return file_modules_comment_commentPb_commentPb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentProjectRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_modules_comment_commentPb_commentPb_proto protoreflect.FileDescriptor

var file_modules_comment_commentPb_commentPb_proto_rawDesc = []byte{
	0x0a, 0x29, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x32, 0x60, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x70, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x52, 0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d,
	0x48, 0x75, 0x62, 0x2f, 0x52, 0x65, 0x74, 0x72, 0x6f, 0x50, 0x47, 0x46, 0x2d, 0x48, 0x75, 0x62,
	0x2d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x47, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_modules_comment_commentPb_commentPb_proto_rawDescOnce sync.Once
	file_modules_comment_commentPb_commentPb_proto_rawDescData = file_modules_comment_commentPb_commentPb_proto_rawDesc
)

func file_modules_comment_commentPb_commentPb_proto_rawDescGZIP() []byte {
	file_modules_comment_commentPb_commentPb_proto_rawDescOnce.Do(func() {
		file_modules_comment_commentPb_commentPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_comment_commentPb_commentPb_proto_rawDescData)
	})
	return file_modules_comment_commentPb_commentPb_proto_rawDescData
}

var file_modules_comment_commentPb_commentPb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_comment_commentPb_commentPb_proto_goTypes = []interface{}{
	(*CreateCommentProjectReq)(nil), // 0: CreateCommentProjectReq
	(*CreateCommentProjectRes)(nil), // 1: CreateCommentProjectRes
}
var file_modules_comment_commentPb_commentPb_proto_depIdxs = []int32{
	0, // 0: CommentGrpcService.CreateCommentProject:input_type -> CreateCommentProjectReq
	1, // 1: CommentGrpcService.CreateCommentProject:output_type -> CreateCommentProjectRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_comment_commentPb_commentPb_proto_init() }
func file_modules_comment_commentPb_commentPb_proto_init() {
	if File_modules_comment_commentPb_commentPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_comment_commentPb_commentPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_comment_commentPb_commentPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_comment_commentPb_commentPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_comment_commentPb_commentPb_proto_goTypes,
		DependencyIndexes: file_modules_comment_commentPb_commentPb_proto_depIdxs,
		MessageInfos:      file_modules_comment_commentPb_commentPb_proto_msgTypes,
	}.Build()
	File_modules_comment_commentPb_commentPb_proto = out.File
	file_modules_comment_commentPb_commentPb_proto_rawDesc = nil
	file_modules_comment_commentPb_commentPb_proto_goTypes = nil
	file_modules_comment_commentPb_commentPb_proto_depIdxs = nil
}
