// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: modules/comment/commentPb/commentPb.proto

package RetroPGF_Hub_Backend_Go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentGrpcServiceClient is the client API for CommentGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentGrpcServiceClient interface {
	CreateCommentProject(ctx context.Context, in *CreateCommentProjectReq, opts ...grpc.CallOption) (*CreateCommentProjectRes, error)
}

type commentGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentGrpcServiceClient(cc grpc.ClientConnInterface) CommentGrpcServiceClient {
	return &commentGrpcServiceClient{cc}
}

func (c *commentGrpcServiceClient) CreateCommentProject(ctx context.Context, in *CreateCommentProjectReq, opts ...grpc.CallOption) (*CreateCommentProjectRes, error) {
	out := new(CreateCommentProjectRes)
	err := c.cc.Invoke(ctx, "/CommentGrpcService/CreateCommentProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentGrpcServiceServer is the server API for CommentGrpcService service.
// All implementations must embed UnimplementedCommentGrpcServiceServer
// for forward compatibility
type CommentGrpcServiceServer interface {
	CreateCommentProject(context.Context, *CreateCommentProjectReq) (*CreateCommentProjectRes, error)
	mustEmbedUnimplementedCommentGrpcServiceServer()
}

// UnimplementedCommentGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommentGrpcServiceServer struct {
}

func (UnimplementedCommentGrpcServiceServer) CreateCommentProject(context.Context, *CreateCommentProjectReq) (*CreateCommentProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommentProject not implemented")
}
func (UnimplementedCommentGrpcServiceServer) mustEmbedUnimplementedCommentGrpcServiceServer() {}

// UnsafeCommentGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentGrpcServiceServer will
// result in compilation errors.
type UnsafeCommentGrpcServiceServer interface {
	mustEmbedUnimplementedCommentGrpcServiceServer()
}

func RegisterCommentGrpcServiceServer(s grpc.ServiceRegistrar, srv CommentGrpcServiceServer) {
	s.RegisterService(&CommentGrpcService_ServiceDesc, srv)
}

func _CommentGrpcService_CreateCommentProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentGrpcServiceServer).CreateCommentProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommentGrpcService/CreateCommentProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentGrpcServiceServer).CreateCommentProject(ctx, req.(*CreateCommentProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentGrpcService_ServiceDesc is the grpc.ServiceDesc for CommentGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CommentGrpcService",
	HandlerType: (*CommentGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommentProject",
			Handler:    _CommentGrpcService_CreateCommentProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/comment/commentPb/commentPb.proto",
}
